0xPolygon/polygon-token-list

src/build.js, src/metadata/crossChain.json, src/tokens/crossChain/arbitrum.json, src/tokens/crossChain/avalanche.json, src/tokens/crossChain/ethereum.json, src/tokens/crossChain/fuse.json, src/tokens/crossChain/gnosis.json, src/tokens/crossChain/moonbeam.json, src/tokens/crossChain/moonriver.json, src/tokens/crossChain/optimism.json, src/tokens/crossChain/polygonPoS.json, src/write.js, test/defaultTest.js
Add additional chains to cross chain tokenlist: Ethereum, Arbitrum, Avalanche, Fuse, Moonriver, Moonbeam, Gnosis and Optimism
=> Add cross chain tokens

src/tokens/polygonTokens.json
Karmaverse: https://karmaverse.io
Karmaverse Zombie: https://karmaverse.io/karmaversezombie
=> Add Karmaverse tokens: KNOT & Serum

src/tokens/polygonTokens.json
Added Kapital DAO Token.
Root token (eth): 0x9625cE7753ace1fa1865A47aAe2c5C2Ce4418569
Child token (matic): 0x8e26032650a389BF9cf16C17C4cd605742f1ef8D
Let me know if you require any signatures or other verification. Thank you.
=> Added Kapital DAO Token

src/tokens/polygonTokens.json
Part of https://github.com/maticnetwork/polygon-token-list/issues/270
=> Add Polkamarkets (POLK) token

src/tokens/polygonTokens.json
=> feat: add BREED token

src/tokens/polygonTokens.json
Hi, we've redeployed our contract and remapped so I need to update the address.
We're also in touch with Parvez to get the old mappings renamed/removed.
Thanks!
=> Update token details for TruStake MATIC Vault Shares

.github/workflows/ecs_prod.yml, .github/workflows/ecs_staging.yml, Dockerfile, nginx.conf, prod-taskdef.json, staging-taskdef.json
Tested staging and prod build through the current test branch before updating back to staging and prod for trigger branch of each.
=> Devops 1422 api polygon tokens staging

.github/workflows/ecs_prod.yml, nginx.conf
Cors fix is tested and found working.
After this PR need to disable features not ready to be published to master and push to master for actual code from master to take affect.
=> Devops 1422 api polygon tokens cors fix

src/tokens/polygonTokens.json
Hello, I've updated the rootTunnelAddress back to the default erc20 tunnel contract as well as the project details for the Kapital DAO Token.
=> Updated KAP token

src/tokens/polygonTokens.json
Adds Noggles (NOGS) to Updates polygonTokens.json.
Closes #393
=> Add Noggles (NOGS)

src/tokens/polygonTokens.json
Closes https://github.com/maticnetwork/polygon-token-list/issues/382
=> Add A3A Token

src/tokens/polygonTestnet.json
**Changes**
- Add testnet tokens to polygonTestnet.json
=> chore: add zkevm test tokens

src/metadata/polygonTestnet.json, src/tokens/polygonTestnet.json
**Changes**
- refactor tag name to customZkevmBridge
- add to metadata
=> chore: rename tag | add metadata

src/tokens/polygonTokens.json
This closes https://github.com/maticnetwork/polygon-token-list/issues/418
=> Add {VERSE}: {Verse} Bitcoin.com Token

src/tokens/polygonTestnet.json
**Changes**
- change zkevm tag to lxly
=> chore(rename): change tag zkevm->lxly

src/tokens/polygonTestnet.json
**Changes**
- Change rootChainBridgeAdapter, childChainBridgeAdapter to originChainBridgeAdapter and wrapperChainBridgeAdapter
=> chore(rename): change adapterContract names

src/tokens/polygonTokens.json
**Changes**
- Disable deposit for MAHA
=> chore: pause MAHA

src/tokens/polygonTokens.json
[ x ] I understand that token listing is not required to use the Polygon Wallet with a token.
Please provide the following information for your token.
Token Name: SelfKey
Token Symbol: KEY
Decimals: 18
Polygon Address: 0x32dC2dD3C2bE453a369625e6Fe0E438aeD814919
Ethereum Address: 0x4cc19356f2d37338b9802aa8e8fc58b0373296e7
Logo URI (svg): https://selfkey.org/wp-content/uploads/2023/10/selfkey.svg
Project Name: SelfKey
Project Summary: SelfKey is a blockchain-based identity platform. The technology provides individuals, companies, exchanges, fintech startups, and banks - with a platform to manage identity data (oftentimes KYC).
Project Contact: [contact@selfkey.org](mailto:contact@selfkey.org)
Project Website: https://selfkey.org/
Mainnet/Testnet: Mainnet
Additonal Notes:
=> Add KEY: SelfKey

src/tokens/polygonTokens.json
**Changes**
Blacklist RLTM
Polygon - https://polygonscan.com/token/0x1b396CF90504686b7edE2760eebb053d30d1f389
Ethereum - https://etherscan.io/token/0x1b396CF90504686b7edE2760eebb053d30d1f389
=> feat: blacklist RLTM

src/tokens/polygon.json, src/tokens/polygonPopular.json, src/tokens/polygonTokens.json
**Changes**
Add custom Dai as cDAI
L1EscrowProxy: https://etherscan.io/address/0x4a27ac91c5cd3768f140ecabde3fc2b2d92edb98#readProxyContract
L2Dai proxy:
https://zkevm.polygonscan.com/address/0x744c5860ba161b5316f7e80d9ec415e2727e5bd5
=> Feat: add custom DAI 

src/tokens/polygon.json, src/tokens/polygonPopular.json, src/tokens/polygonTokens.json, src/tokens/popularTokens.json
**Changes**
- Pause deposit and withdraw for WRLD
https://0xpolygon.slack.com/archives/C03NMQ2PUE8/p1699975588695889?thread_ts=1699907624.794209&cid=C03NMQ2PUE8
=> chore: pause deposit and withdraw - WRLD

src/tokens/polygon.json, src/tokens/polygonPopular.json
**Changes**
- Change Dai - Custom to Dai
=> chore: rename dai

src/tokens/polygonTokens.json
[ x ] I understand that token listing is not required to use the Polygon Wallet with a token.
Please provide the following information for your token.
Token Name: KeyFi
Token Symbol: KEYFI
Decimals: 18
Polygon Address: 0x96fC3568D36b236121Ef3dd3EDEb31CA8d08bfb0
Ethereum Address: 0xb8647e90c0645152fccf4d9abb6b59eb4aa99052
Logo URI: https://keyfi.com/Blue-only-logo.svg
Project Name: KeyFi
Project Summary: KeyFi is an app-based platform for managing decentralized finance (DeFi).
Project Contact: [vincent@keyfi.com](mailto:vincent@keyfi.com)
Project Website: https://keyfi.com/
Mainnet/Testnet: Mainnet
=> add KeyFi: KEYFI

src/tokens/polygonTokens.json
update taki logo to identify it's a wormhole token, updated website, and contact email
=> update taki logo, contact email, and website

src/tokens/mappedTokens.json
Add no deposit tag for DOGEGF token
=> mod: no deposit tag for DOGEGF token

src/tokens/mappedTokens.json
Fixed the tag on eth and added no deposit on dogegf
=> Block dogegf token

prod-taskdef.json
=> Datadog integration with eu

wrangler.toml
=> changing format for routes
